version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First build
          command: gradle test
  build:
    docker:
      - image: alpine:latest
    steps:
      - run: echo hello


workflows:
  version: 2
  one_and_two:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master